### ISSUE TITLE
is it possible to auth against IAM password?

### ISSUE THREAD

**Issue by TheCase** [denismo/aws-iam-ldap-bridge#14]
as opposed to a Secret Key.

**Comment by micyoung70** [comment]
@denismo, thanks for all your hard work on this! I am looking at using this authentication solution, and I have found a bit of a quirk. I have set "validator=iam_password" in /etc/iam_ldap.conf but I am only seeing users imported that have an access key. For security reasons, we normally don't create access keys for users.

This behavior seems like a bit of a legacy with the iam_secret_key option and shouldn't really apply to iam_password option. Instead, the sync code only import users that have passwords.

Thoughts? A fix maybe? ;)

**Comment by micyoung70** [comment]
Note that I am using the ami-19533f23 image for testing. It's possible that is out of date with your change here.

**Comment by denismo** [comment]
Yep, an oversight, thanks for raising it. Can't promise a fix soon though.

Denis

**Comment by mysysadmin-ltd** [comment]
@denismo - thank you for your work on this.
What attribute is the password stored under?
I don't see a password-like attribute when I use ldapsearch, even with ads-dspasswordhidden set to FALSE.
Cheers,
David

**Comment by denismo** [comment]
It's not stored, for security reasons.

**Comment by mysysadmin-ltd** [comment]
Thanks for the quick response :-)
I'm attempting to get a Rundeck installation to authenticate against this (http://rundeck.org/2.6.1/administration/authenticating-users.html#ldap).
I suspect Rundeck is looking for a password in ApacheDS to match against - or does it get passed through to IAM?
I may have totally the wrong end of the stick here - it's been a long while since I've used LDAP in anger...

**Comment by denismo** [comment]
Thanks for clarifying. Not familiar with Rundeck. Password feature does work with PAM-LDAP, which I believe uses password during bind. It does not look for any password attributes. Is there a way to configure Rundeck to bind using the requested user and their password? Alternatively, I checked that it supports login-vi-pam. If you then configure PAM-LDAP then it might work.

**Comment by mysysadmin-ltd** [comment]
Cheers - good suggestion. I have a bit of a hacky workaround working now based on PAM-LDAP - the hacky bit is to do with the Rundeck/PAM end of things, not the LDAP/IAM end - i.e. your bit is working nicely, thank you!
