### ISSUE TITLE
Could not find public AMIs

### ISSUE THREAD

**Issue by yclian** [denismo/aws-iam-ldap-bridge#20]
```
* aws_instance.ldap: Error launching source instance: InvalidAMIID.NotFound: The image id '[ami-d19df4eb]' does not exist
        status code: 400, request id:
```

Is there a new AMI available or we have to bake this ourselves?

**Comment by jweede** [comment]
Check the `ap-southeast-2` region

**Comment by yclian** [comment]
@jweede Thanks.

**Comment by yclian** [comment]
@jweede Still trying:

```
root@cb84c5395106:/usr/src/app# python ec2_ami_copy.py -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -r ap-southeast-2 -i ami-d19df4eb
2016-04-07 08:32:51,280 CRITICAL: Getting the snapshot of the source AMI failed: The snapshot 'snap-fb35c8f2' does not exist.
```

**Comment by yclian** [comment]
From the Web Console, this is the error, after pressing "Copy AMI":

```
You do not have permission to access the storage of this ami
```

**Comment by yclian** [comment]
I closed it because:

 1. It's a region issue at the first place (probably `README.md` has to be updated).
 2. Issue on copying AMI is not your problem.
 3. I overcame this by launching an instance by hand (and I will deal with the AMI copying issue from there).

**Comment by yclian** [comment]
Reopened. Apparently point 3 of my previous comment isn't valid, I couldn't copy my AMI created from the instance due to storage permission. I will still need you to make your AMI available in my zone (us-west-2), can you?

Thanks.

**Comment by denismo** [comment]
Sure, I'll fix that. Can't do it today though, under pressure with something else, give me couple of days. I'll also update the README.
Denis

**Comment by yclian** [comment]
@denismo Thanks, I can wait. I do not know if it's possible: if you don't have to do an AMI copy but adjust the permission of the storage, that will fix the issue too.

**Comment by denismo** [comment]
Yes, I think I should be able to just adjust the permissions. It should be possible to copy the AMI then.

**Comment by yclian** [comment]
Btw, I did my own "packer"-ing and I managed to built my own AMI (but a Ubuntu instead) for this. That said, it serves almost 0 benefit now if you work on the permission.

**Comment by yclian** [comment]
Created a PR with some improvements on doc.

**Comment by denismo** [comment]
Thanks for reporting anyway, I made the snapshot public
